import type { Metadata, Viewport } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Header from "./_components/header";
import Sidebar from "./_components/sidebar";
import { Suspense } from "react";
import Loading from "@/components/ui/loading";
import { IsleofDucks } from "@/discord/discordUtils";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
    themeColor: IsleofDucks.themeColour,
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    
    return (
        <ClerkProvider appearance={{ baseTheme: dark }}>
            {/* ClerkProvider already includes the html tag */}
            <html suppressHydrationWarning lang="en">
                <body className={`flex flex-col min-h-screen dark:bg-neutral-800`}>
                    <Header />
                    <div className="flex flex-grow">
                        <Sidebar />
                        <main className="flex flex-col flex-grow w-full gap-4 m-8">
                            <Suspense fallback={<Loading />}>
                                {children}
                            </Suspense>
                        </main>
                    </div>
                </body>
            </html>
        </ClerkProvider>
    );
}
